### ISSUE TITLE
Section "Routing with Compojure" refers to deprecated Compojure namespace

### ISSUE THREAD

**Issue by teodorlu** [http-kit/http-kit.github.com#39]
Hello!

I just had some trouble getting the [Compojure example on http-kit.org](http://www.http-kit.org/server.html#routing) running. Turns out [compojure.handler is deprecated](https://weavejester.github.io/compojure/compojure.handler.html), and does not work with the latest Compojure version (1.6).

Consider modifying the example?

Thanks for a great library! Regards,
Teodor

**Comment by teodorlu** [comment]
I cooked up something like this:

```clojure
(ns preik.core
  (require [compojure.core :refer [defroutes GET]]
           [compojure.route :as route]
           [org.httpkit.server :as server]
           [ring.middleware.defaults :refer [wrap-defaults site-defaults]]
           ))

(defroutes app-routes
  (GET "/" [] "Hello, world!")
  (GET "/user" [] "You're looking for a user.")
  (route/not-found "Can't find what you're looking for.")
  )

(def app
  (wrap-defaults app-routes site-defaults))
```

which lets me `(server/run-server app {:port 3001})`.

**Comment by 0atman** [comment]
Thanks @teodorlu, sorry we didn't reply when you reported this, are the docs now fixed? I can't find a reference to `compojure.handler` on the page.

**Comment by teodorlu** [comment]
No worries. Open Source shouldn't be guilt-tripping.

Documentation looks good to me now. Feel free to close!

Teodor

**Comment by 0atman** [comment]
Wonderful! I'll try be more responsive in the future :-)

**Comment by teodorlu** [comment]
No problem!
